In [9]:
# Please ensure 1. miniconda has been installed in your system; 2. visual studio code can use 'Python: Select your interpreter' (Press F1 and search this) to find the miniconda's python interpreter path; 3. The top-right has been correctly shown the python kernel
import torch

1. Write a program to create a tensor of 10 zeros, 10 ones, 10 fives

In [11]:
### start your implementation here ###

### end your implementation here ###
print("A tensor of 10 zeros:")
print(x)

### start your implementation here ###
### end your implementation here ###
print("\nA tensor of 10 ones:")
print(x)

### start your implementation here ###
### end your implementation here ###
print("\nA tensor of 10 fives:")
print(x)

A tensor of 10 zeros:
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

A tensor of 10 ones:
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

A tensor of 10 fives:
tensor([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])


2. Write a program to create a tensor of the integers from 30 to 70.

In [12]:
### start your implementation here ###

### end your implementation here ###
print("Tensor of the integers from 30 to 70")
print(x)

Tensor of the integers from 30 to 70
tensor([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
        48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
        66, 67, 68, 69, 70])


3. Write a program to create a 3x3 identity matrix.

In [14]:
### start your implementation here ###

### end your implementation here ###
print('3x3 matrix:')
print(x)

3x3 matrix:
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


4. Write a program to create a 10x10 matrix, in which the elements on the borders will be equal to 1, and inside 0.

In [35]:
### start your implementation here ###

### end your implementation here ###
print(x)

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])


5. Write a program to create a 4x4 matrix in which 0 and 1 are staggered, with zeros on the main diagonal.

In [32]:
### start your implementation here ###

### end your implementation here ###
print(x)

tensor([[0., 1., 0., 1.],
        [1., 0., 1., 0.],
        [0., 1., 0., 1.],
        [1., 0., 1., 0.]])


6. Write a program to create a 4x4 with ascending values from 0~15, now create a new x from the said x swapping first and last rows.

In [36]:
x = torch.arange(16).reshape(-1, 4)
print("Original x:")
print(x)
print("\nNew x after swapping first and last rows of the said x:")
### start your implementation here ###

### end your implementation here ###
print(x)

Original x:
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])

New x after swapping first and last rows of the said x:
tensor([[12, 13, 14, 15],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [ 0,  1,  2,  3]])


7. Write a program to Create a 1-D x of 30 evenly spaced elements between 2.5. and 6.5, inclusive.

In [37]:
x = None

### start your implementation here ###

### end your implementation here ###
print(x)

tensor([2.5000, 2.6379, 2.7759, 2.9138, 3.0517, 3.1897, 3.3276, 3.4655, 3.6034,
        3.7414, 3.8793, 4.0172, 4.1552, 4.2931, 4.4310, 4.5690, 4.7069, 4.8448,
        4.9828, 5.1207, 5.2586, 5.3966, 5.5345, 5.6724, 5.8103, 5.9483, 6.0862,
        6.2241, 6.3621, 6.5000])


8. Write a program to replace all elements of x that are greater than 0.5 to be 0.5.

In [38]:
x = torch.tensor([[ 0.42436315, 0.48558583, 0.32924763], [ 0.7439979,0.58220701,0.38213418], [ 0.5097581,0.34528799,0.1563123 ]])
print("Original x:")
print(x)
print("Replace all elements of the said x with .5 which are greater than .5")
### start your implementation here ###

### end your implementation here ###
print(x)

Original x:
tensor([[0.4244, 0.4856, 0.3292],
        [0.7440, 0.5822, 0.3821],
        [0.5098, 0.3453, 0.1563]])
Replace all elements of the said x with .5 which are greater than .5
tensor([[0.4244, 0.4856, 0.3292],
        [0.5000, 0.5000, 0.3821],
        [0.5000, 0.3453, 0.1563]])


9. Write a program to stack xs in sequence horizontally (column wise).

In [42]:
print("\nOriginal xs:")
x = torch.arange(9).reshape(3,3)
y = x*3
print("x-1")
print(x)
print("x-2")
print(y)

new_x = None
### start your implementation here ###

### end your implementation here ###
print("\nStack xs in sequence horizontally:")
print(new_x)


Original xs:
x-1
tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
x-2
tensor([[ 0,  3,  6],
        [ 9, 12, 15],
        [18, 21, 24]])

Stack xs in sequence horizontally:
tensor([[ 0,  1,  2,  0,  3,  6],
        [ 3,  4,  5,  9, 12, 15],
        [ 6,  7,  8, 18, 21, 24]])


10. Write a program to stack arrays in sequence vertically.

In [46]:
print("\nOriginal arrays:")
x = torch.arange(9).reshape(3,3)
y = x*3
print("Array-1")
print(x)
print("Array-2")
print(y)

### start your implementation here ###

### end your implementation here ###
print("\nStack arrays in sequence vertically:")
print(new_x)


Original arrays:
Array-1
tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
Array-2
tensor([[ 0,  3,  6],
        [ 9, 12, 15],
        [18, 21, 24]])

Stack arrays in sequence vertically:
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 0,  3,  6],
        [ 9, 12, 15],
        [18, 21, 24]])


11. Write a program to extract first, third and fifth elements of the third and fifth rows from a given (6x6) x.

In [50]:
x = torch.arange(0,36).reshape((6, 6))
print("Original x:")
print(x)
print("\nExtracted data: First, third and fifth elements of the third and fifth rows")

### start your implementation here ###

### end your implementation here ###

Original x:
tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]])

Extracted data: First, third and fifth elements of the third and fifth rows
tensor([[12, 14, 16],
        [24, 26, 28]])


12. Write a program to check whether a x contains a specified row.

In [54]:
x = torch.arange(20).reshape(4,5)
print("Original x:")
print(x)
### start your implementation here ###
 #check if [0, 1, 2, 3, 4] is in arr1
 #check if [0, 1, 2, 3, 5] is in arr1
 #check if [15, 16, 17, 18, 19] is in arr1
### end your implementation here ###

Original x:
tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])
tensor(True)
tensor(False)
tensor(True)


13. Write a program to compute the multiplication of two given matrixes.

In [58]:
p = torch.tensor([[1, 0], [0, 1]])
q = torch.tensor([[1, 2], [3, 4]])
print("original matrix:")
print(p)
print(q)

### start your implementation here ###

### end your implementation here ###
print("\nResult of the said matrix multiplication:")
print(result)

original matrix:
tensor([[1, 0],
        [0, 1]])
tensor([[1, 2],
        [3, 4]])

Result of the said matrix multiplication:
tensor([[1, 2],
        [3, 4]])


14. Write a program to compute the outer product of two given vectors.

In [60]:
p = torch.tensor([1, 0, 0, 1])
q = torch.tensor([1, 2, 3, 4])
print("original matrix:")
print(p)
print(q)

### start your implementation here ###

### end your implementation here ###
print("\nOuter product of the said two vectors:")
print(result)

original matrix:
tensor([1, 0, 0, 1])
tensor([1, 2, 3, 4])

Outer product of the said two vectors:
tensor([[1, 2, 3, 4],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [1, 2, 3, 4]])


15. Write a program to create a 5x5 x with random values and find the minimum and maximum values.

In [64]:
torch.manual_seed(123)
x = torch.rand(5,5)
print("Original x:")
print(x)

### start your implementation here ###

### end your implementation here ###
print("\nMinimum and Maximum Values:")
print(xmin, xmax)

Original x:
tensor([[0.2961, 0.5166, 0.2517, 0.6886, 0.0740],
        [0.8665, 0.1366, 0.1025, 0.1841, 0.7264],
        [0.3153, 0.6871, 0.0756, 0.1966, 0.3164],
        [0.4017, 0.1186, 0.8274, 0.3821, 0.6605],
        [0.8536, 0.5932, 0.6367, 0.9826, 0.2745]])

Minimum and Maximum Values:
tensor(0.0740) tensor(0.9826)


16. Write a program to normalize a 3x3 random matrix following `x = (x - min)/(max - min)`.

In [65]:
torch.manual_seed(123)
x = torch.rand(3,3)
print("Original x:")
print(x)
### start your implementation here ###

### end your implementation here ###
print("\nAfter normalization:")
print(x)

Original x:
tensor([[0.2961, 0.5166, 0.2517],
        [0.6886, 0.0740, 0.8665],
        [0.1366, 0.1025, 0.1841]])

After normalization:
tensor([[0.2803, 0.5584, 0.2242],
        [0.7755, 0.0000, 1.0000],
        [0.0790, 0.0360, 0.1389]])


17. Write a program to find the nearest value from a given value(0.5) in an x.

In [69]:
torch.manual_seed(123)
x = torch.rand(10)
v = 0.5
n = None
### start your implementation here ###

### end your implementation here ###
print(n)

tensor(0.5166)


18. Write a program to create random vector of size 15 and replace the maximum value by -1.

In [70]:
torch.manual_seed(123)
x = torch.rand(15)
print("Original x:")
print(x)

### start your implementation here ###

### end your implementation here ###
print("\nMaximum value replaced by -1:")
print(x)

Original x:
tensor([0.2961, 0.5166, 0.2517, 0.6886, 0.0740, 0.8665, 0.1366, 0.1025, 0.1841,
        0.7264, 0.3153, 0.6871, 0.0756, 0.1966, 0.3164])

Maximum value replaced by -1:
tensor([ 0.2961,  0.5166,  0.2517,  0.6886,  0.0740, -1.0000,  0.1366,  0.1025,
         0.1841,  0.7264,  0.3153,  0.6871,  0.0756,  0.1966,  0.3164])


19. Write a program to get the n largest values of an x.

In [73]:
torch.manual_seed(123)
x = torch.rand(10)
print("Original x:")
print(x)

n = 3
### start your implementation here ###

### end your implementation here ###
print (f"\n{n}-largest values: ", result)

Original x:
tensor([0.2961, 0.5166, 0.2517, 0.6886, 0.0740, 0.8665, 0.1366, 0.1025, 0.1841,
        0.7264])

3-largest values:  tensor([0.8665, 0.7264, 0.6886])


20. Write a program to get the floor, ceiling and truncated values of the elements of x.

In [74]:
x = torch.tensor([-1.6, -1.5, -0.3, 0.1, 1.4, 1.8, 2.0])
print("Original x:")

print("\nFloor values of the above x elements:")
### start your implementation here ###

### end your implementation here ###

print("\nCeil values of the above x elements:")
### start your implementation here ###

### end your implementation here ###

print("\nTruncated values of the above x elements:")
### start your implementation here ###

### end your implementation here ###

Original x:

Floor values of the above x elements:
tensor([-2., -2., -1.,  0.,  1.,  1.,  2.])

Ceil values of the above x elements:
tensor([-1., -1., -0.,  1.,  2.,  2.,  2.])

Truncated values of the above x elements:
tensor([-1., -1., -0.,  0.,  1.,  1.,  2.])


21. Write a program to calculate the probabilities given the unnormalized logits (Refer to Deep Learning - Part I - Softmax Loss).

In [76]:
torch.manual_seed(123)
num_classes = 10
logits = torch.rand(num_classes)

### start your implementation here ###

### end your implementation here ###

print(prob)
print(prob.sum()) # check if prob is summed up to 1.

tensor([0.0880, 0.1097, 0.0842, 0.1303, 0.0705, 0.1557, 0.0750, 0.0725, 0.0787,
        0.1353])
tensor(1.)


22. Write a program to calculate the probabilities given the unnormalized logits. Here, the x of logits is of 2 dimensions: `(num_samples x num_classes)`. Figure out the probabilities for each sample.

In [77]:
torch.manual_seed(123)

num_samples = 4
num_classes = 10

logits = torch.rand(num_samples, num_classes)
### start your implementation here ###

### end your implementation here ###
print(prob)
print(prob.sum(1)) # check: for each sample, prob is summed up to 1.

tensor([[0.0880, 0.1097, 0.0842, 0.1303, 0.0705, 0.1557, 0.0750, 0.0725, 0.0787,
         0.1353],
        [0.0894, 0.1296, 0.0703, 0.0794, 0.0895, 0.0974, 0.0734, 0.1492, 0.0956,
         0.1262],
        [0.1227, 0.0945, 0.0988, 0.1396, 0.0687, 0.1009, 0.0690, 0.1231, 0.1284,
         0.0543],
        [0.1395, 0.1156, 0.1132, 0.1119, 0.1380, 0.0852, 0.0596, 0.0789, 0.0640,
         0.0941]])
tensor([1.0000, 1.0000, 1.0000, 1.0000])


23. Write a program to calculate the Softmax Loss given the unnormalized logits and the ground-truth labels of the samples. Here, the shape of logits is: `(num_samples x num_classes)` and the shape of GT labels is `(num_samples,)`, each of which is the corresponding label for that sample. Figure out the total Softmax Loss.

In [78]:
torch.manual_seed(123)

n_samples = 4
n_classes = 10

logits = torch.rand(n_samples, n_classes)
labels = torch.randint(0, 10, size=(n_samples,))

### start your implementation here ###

### end your implementation here ###

print(loss)

tensor(2.4774)


24. Write a program to calculate the accuracy for classification. Given the output logits of the model (`num_samples x num_classes`) and the ground-truth labels of corresponding samples (`num_samples`,), calculate the accuracy of the classification result.

In [81]:
torch.manual_seed(123)

n_samples = 100
n_classes = 20

logits = torch.rand(n_samples, n_classes)
labels = torch.randint(0, n_classes, (n_samples,))

### start your implementation here ###

### end your implementation here ###

print(acc)

tensor(0.0300)


25. Write a program to calculate the precision, recall and f1-score for a binary-classification problem:

(1). Given the output of a model (`num_samples`,), calculate the probability of being class-1 by implementing a sigmoid function, i.e., $p(x=1)=sigmoid(output)$.

(2). Suppose we use a threshold $\tau=0.5$, and if $p(x)>\tau$, the model will predict the corresponding sample as class-1, else class-0.

(3). Compare the model predictions with the given ground-truth labels (`num_samples`,), and calculate the precision, recall of class-1.

In [93]:
torch.manual_seed(123)
n_samples = 100
thres = 0.5
r = 0.7

labels = torch.randint(0,1+1, size=(n_samples,))
outp = torch.randn((n_samples,))

# sigmoid function
def sigmoid(x):
    ### start your implementation here ###

    ### end your implementation here ###
    
p = sigmoid(outp)
### start your implementation here ###
# ...
pred = p > thres
### end your implementation here ###

# TP of class-1
### start your implementation here ###
# tp =  # true positive
### end your implementation here ###

# recall of class-1
### your implementation here ###
# recall = ...
### your implementation here ###

# precision of class-1
### start your implementation here ###
# prec = ...
### end your implementation here ###

print(f"recall of class-1: {recall}, precision of class-1:{prec}.")

recall of class-1: 0.35555556416511536, precision of class-1:0.35555556416511536.
